### ISSUE TITLE
GIMX Integration?

### ISSUE THREAD

**Issue by Conzar** [AterialDawn/Nintendo-Switch-Pro-Controller-AVR-Firmware#1]
Have you attempted to integrate with GIMX?  If not, where in this repo can information be found about the switch?

Information like:

* Vendor ID
* Device Name
* Masks for the buttons, axis, etc
* bit lengths
* Names

Thank you

**Comment by AterialDawn** [comment]
Thanks for the interest in this project!

Unfortunately, I have no interest in integrating this with GIMX as that is matlos' project. I have submitted this code to him so that he may work on integrating it with GIMX if he so chooses.

In response to the other info, the descriptor stuff may be seen in Descriptors.c, it's a binary dump of the descriptors sent over to the switch using a real Switch Pro controller, further below are also some strings for said descriptors. The button stuff is in serialProto.c, the relevant locations for the data should be in there.

Extra information that would help with decoding/encoding the relevant packets were partially obtained from [this link](https://github.com/mfosse/JoyCon-Driver/blob/master/joycon-driver/src/main.cpp#L204)

If you have any more questions, i'll do my best to answer them.

**Comment by Conzar** [comment]
Thank you
